print('ingrese 20 numeros para saber cual es el mayor y cual el menor')
a=int(input('ingrese un numero'))
b=int(input('ingrese un numero'))
c=int(input('ingrese un numero'))
d=int(input('ingrese un numero'))
e=int(input('ingrese un numero'))
f=int(input('ingrese un numero'))
g=int(input('ingrese un numero'))
h=int(input('ingrese un numero'))
i=int(input('ingrese un numero'))
j=int(input('ingrese un numero'))
k=int(input('ingrese un numero'))
l=int(input('ingrese un numero'))
m=int(input('ingrese un numero'))
n=int(input('ingrese un numero'))
o=int(input('ingrese un numero'))
p=int(input('ingrese un numero'))
q=int(input('ingrese un numero'))
r=int(input('ingrese un numero'))
s=int(input('ingrese un numero'))
t=int(input('ingrese un numero'))
lista=[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t]
print('los numeros ingresados son: ',lista)
lista.sort()
print('el numero menor es: ',lista[0])
print('el mayor es: ',lista[19])
