# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGVakcNx1iog8G3r699b5a9HsNaCZyiO
"""

import random
from enum import IntEnum

class Juego(IntEnum):
    Piedra = 0
    Papel = 1
    Tijeras = 2
    Pistola = 3
    Agua = 4
    Fuego = 5
    Aire = 6
    Árbol = 7
    Humano = 8
    Dragón = 9
    Relámpago = 10
    Demonio = 11
    Esponja = 12
    Lobo = 13
    Serpiente = 14

def Seleccion_Usuario():
    elecciones = [f"{juego.name}[{juego.value}]" for juego in Juego]
    elecciones_str = ", ".join(elecciones)
    Seleccion = int(input(f"Introduzca una opción ({elecciones_str}): "))
    juego = Juego(Seleccion)
    return juego

def Seleccion_PC():
    Seleccion = random.randint(0, len(Juego) - 1)
    juego = Juego(Seleccion)
    return juego

def Determinar_Ganador(juego_usuario, juego_PC):
    if juego_usuario == juego_PC:
        print(f"Ambos jugadores seleccionaron {juego_usuario.name}. Esto es un empate!")
        
    elif juego_usuario == Juego.Piedra:
        if juego_PC == Juego.Tijeras:
            print("¡La piedra rompe las tijeras! Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Aire:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Papel:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Agua:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")
            
    elif juego_usuario == Juego.Papel:
        if juego_PC == Juego.Tijeras:
            print("¡Las tijeras cortan al papel! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Agua:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Fuego:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Piedra:
            print("¡BLa bla bla ! Tú ganas.")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla ! Tú ganas.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganass.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")

    elif juego_usuario == Juego.Tijeras:
        if juego_PC == Juego.Piedra:
            print("¡La piedra aplasta a las tijeras! ¡Tú pierdes!")
        elif juego_PC == Juego.Papel:
            print("Las tijeras cortan al papel, ¡tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Agua:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla ! Tú ganas.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla ! Tú ganas.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")
            
    elif juego_usuario == Juego.Pistola:
        if juego_PC == Juego.Piedra:
            print("Sí, sí, sí, tú ganas.")
        elif juego_PC == Juego.Papel:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Tijeras:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Aire:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Agua:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")

    elif juego_usuario == Juego.Agua:
        if juego_PC == Juego.Piedra:
            print("¡El agua le gana a la piedra! ¡Tú ganas!")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Fuego:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")

    elif juego_usuario == Juego.Fuego:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Perdiste.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")

    elif juego_usuario == Juego.Aire:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! ¡Tú ganas!.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla ! Tú ganas.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla ! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")
            
    elif juego_usuario == Juego.Árbol:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Perdiste.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! Tú pierdes")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Humano:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")

    elif juego_usuario == Juego.Humano:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! Tú pierdes")
        elif juego_PC == Juego.Dragón:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")
            
    elif juego_usuario == Juego.Dragón:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú ganas.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! Tú ganas")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")
      
    elif juego_usuario == Juego.Relámpago:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú ganas.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")

    elif juego_usuario == Juego.Demonio:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú ganas.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú ganas.")

    elif juego_usuario == Juego.Esponja:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")
        
    elif juego_usuario == Juego.Lobo:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! ¡Tú ganas!.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Serpiente:
            print("¡BLa bla bla! Tú pierdes.")
        
    elif juego_usuario == Juego.Serpiente:
        if juego_PC == Juego.Piedra:
            print("¡Bla bla bla! Tú pierdes.")
        elif juego_PC == Juego.Papel:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Tijeras:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Pistola:
            print("¡Bla bla bla! ¡Tú pierdes!")
        elif juego_PC == Juego.Humano:
            print("¡Bla bla bla! ¡Tú ganas!")
        elif juego_PC == Juego.Aire:
            print("¡BLa bla bla! ¡Tú ganas!.")
        elif juego_PC == Juego.Árbol:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Fuego:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Dragón:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Relámpago:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Demonio:
            print("¡BLa bla bla! Tú pierdes.")
        elif juego_PC == Juego.Esponja:
            print("¡BLa bla bla! Tú ganas.")
        elif juego_PC == Juego.Lobo:
            print("¡BLa bla bla! Tú ganas.")

while True:
    try:
        Juego_User = Seleccion_Usuario()
        print("El Usuario ha seleccionado", Juego_User, "para competir",)
    
    except ValueError as e:
        range_str = f"[0, {len(Juego) - 1}]"
        print(f"Selección invalida. Introduzca un valor en el rango {range_str}")
        continue

    Juego_PC = Seleccion_PC()
    print("El PC ha seleccionado", Juego_PC, "para competir",)
    Determinar_Ganador(Juego_User, Juego_PC)

    Jugar_Nuevamente = input("¿Juega de nuevo? (SI (1)/NO (2)): ")
    if Jugar_Nuevamente == 2:
      break